# Generated by Django 4.1.2 on 2022-11-29 01:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('description', ckeditor.fields.RichTextField(max_length=50)),
                ('value', models.IntegerField(max_length=10)),
            ],
        ),
    ]
