# Generated by Django 4.1.2 on 2022-11-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_orderstate'),
        ('configuration', '0002_score'),
    ]

    operations = [
    ]
