# Generated by Django 4.1.2 on 2022-11-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_merge_0002_orderstate_0002_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-value']},
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(),
        ),
    ]
